### ISSUE TITLE
Create tests for the component

### ISSUE THREAD

**Issue by j414j** [jalaj711/react-round-progress#1]
Before publishing the component to NPM, it is always better to have the code tested. Therefore, the purpose of this issue is to facilitate and track progress on creating thorough tests for the main component.

**Comment by oktak** [comment]
Hi, I would like to take this for participating in Hacktoberfest, may I?

I am going to use `jest` and to test, and also ` jest-canvas-mock` to check the output.

**Comment by j414j** [comment]
Sure. I am assigning you the issue.

**Comment by j414j** [comment]
Fixed in #2
